CREATE TABLE DIM_ORDER_CHANNEL (
--DDL DE DW_CAFETERIA

	CHANNEL_ID INT PRIMARY KEY,
	CHANNEL_NAME VARCHAR(50)
)

CREATE TABLE DIM_REGION(
	REGION_ID INT PRIMARY KEY,
	REGION_NAME VARCHAR(50)
)

CREATE TABLE DIM_STORES(
	STORE_ID VARCHAR(20) PRIMARY KEY,
	REGION_ID INT,
	LOCATION_TYPE VARCHAR(50)
	
	CONSTRAINT FK_REGION FOREIGN KEY (REGION_ID) REFERENCES DIM_REGION(REGION_ID)
)

CREATE TABLE DIM_CUSTOMERS(
	CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
	AGE_GROUP VARCHAR(20),
	GENDER VARCHAR(20),
	REWARDS_MEMBER CHAR(1)
)

CREATE TABLE DIM_TIME(
	ORDER_TIME DATETIME PRIMARY KEY,
	HOUR INT,
	AM_PM VARCHAR(2)
)

CREATE TABLE DIM_DATE(
	ORDER_DATE DATE PRIMARY KEY,
	SEMESTER INT,
	TRIMESTER INT,
	WEEK INT, 
	MONTH INT,
	DAY INT
)

CREATE TABLE DIM_DRINK_CATEGORIES(
	CATEGORY_ID INT PRIMARY KEY,
	CATEGORY_NAME VARCHAR(50)
)

CREATE TABLE DIM_ORDER_DETAILS(
	ORDER_ID VARCHAR(20) PRIMARY KEY,
	CATEGORY_ID INT,
	CART_SIZE INT, 
	NUM_CUSTOMIZATION INT,
	TOTAL_SPEND FLOAT
	
	CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES DIM_DRINK_CATEGORIES(CATEGORY_ID)
)

CREATE TABLE HECHOS_ORDEN(
	ORDER_ID VARCHAR(20) PRIMARY KEY,
	CUSTOMER_ID VARCHAR(20),
	STORE_ID VARCHAR(20),
	CHANNEL_ID INT,
	ORDER_DATE DATE, 
	ORDER_TIME DATETIME,
	
	CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_ID) REFERENCES DIM_ORDER_DETAILS(ORDER_ID),
	CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMERS(CUSTOMER_ID),
	CONSTRAINT FK_STORE FOREIGN KEY (STORE_ID) REFERENCES DIM_STORES(STORE_ID),
	CONSTRAINT FK_CHANNEL FOREIGN KEY (CHANNEL_ID) REFERENCES DIM_ORDER_CHANNEL(CHANNEL_ID),
	CONSTRAINT FK_ORDER_DATE FOREIGN KEY (ORDER_DATE) REFERENCES DIM_DATE(ORDER_DATE),
	CONSTRAINT FK_ORDER_TIME FOREIGN KEY (ORDER_TIME) REFERENCES DIM_TIME(ORDER_TIME),
)